version: '3'
services:
  db:
    image: postgres:latest
    container_name: livelygrit_db
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: livelygrit_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: livelygrit_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: your_pgadmin_email
      PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin:
